# Generated by Django 4.1 on 2023-11-14 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=20, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(max_length=20, verbose_name='Segundo Apellido')),
                ('edad', models.IntegerField(max_length=3, verbose_name='Edad')),
                ('zona1', models.CharField(max_length=20, verbose_name='Comunidad Autonoma')),
                ('zona2', models.CharField(max_length=20, verbose_name='Provincia')),
                ('zona3', models.CharField(max_length=20, verbose_name='Municipio')),
                ('correo', models.EmailField(max_length=30, verbose_name='Direccion de correo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Numero Telefonico')),
                ('imagen', models.ImageField(null=True, upload_to='media/', verbose_name='Imagen')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
