# Generated by Django 4.1 on 2023-11-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='zona1',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='zona2',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='zona3',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='zona',
            field=models.CharField(default='zona', max_length=20, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
    ]
