# Generated by Django 4.1 on 2023-11-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuarios_zona1_remove_usuarios_zona2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='apellido1',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='apellido2',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=40, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='trabajo',
            field=models.CharField(default='Ocupacion', max_length=30, verbose_name='Ocupacion'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
    ]
