# Generated by Django 4.1 on 2023-11-23 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuarios_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='edad',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nac',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento'),
        ),
    ]
