# Generated by Django 4.1 on 2023-11-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Nombre del taller')),
                ('presentacion', models.TextField(verbose_name='Presentación del taller')),
                ('competencias', models.TextField(verbose_name='Competencias que vas a adquirir')),
                ('objetivos', models.TextField(verbose_name='Objetivo')),
                ('dirigido', models.TextField(verbose_name='Dirigido a')),
                ('mod_dur_valor', models.TextField(verbose_name='Modalidad, duración y valor')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'ordering': ['-created'],
            },
        ),
    ]
