# Generated by Django 4.1 on 2023-12-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talleres',
            name='image',
            field=models.ImageField(default='assets/default.jpg', null=True, upload_to='media/', verbose_name='Imagen'),
        ),
    ]
