# Generated by Django 4.1 on 2023-11-29 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Nombre del curso')),
                ('presentacion', models.TextField(verbose_name='Presentación del curso')),
                ('image', models.ImageField(default='assets/default.jpg', null=True, upload_to='media/', verbose_name='Imagen')),
                ('competencias', models.TextField(verbose_name='Competencias que vas a adquirir')),
                ('objetivos', models.TextField(verbose_name='Objetivo')),
                ('dirigido', models.TextField(verbose_name='Dirigido a')),
                ('mod_dur_valor', models.TextField(verbose_name='Modalidad, duración y valor')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de inscripcion')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
    ]
