# Generated by Django 4.1 on 2023-11-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='image',
            field=models.ImageField(default='assets/default.jpg', null=True, upload_to='media/', verbose_name='Imagen'),
        ),
    ]
